
export const Types = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    TOGGLE_CART_HIDEN: 'TOGGLE_CART_HIDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEEM: 'REMOVE_ITEEM',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    UPDATED_SHOP_DATA: 'UPDATED_SHOP_DATA'
};

