export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TOGGLE_CART_HIDEN = 'TOGGLE_CART_HIDEN';


export const Types = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    TOGGLE_CART_HIDEN: 'TOGGLE_CART_HIDEN'
}

